### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by S6savahd** [ceurws/ToolsEswc#16]
now looking into the dataset, I see license is missing for some of the volumes for example:
vol-1
vol-1557
.
.
.

**Comment by S6savahd** [comment]
not for all, but for some.

**Comment by liyakun** [comment]
@S6savahd  the provided license information is not complete by the previous script, do you still have it? 
By the way, it seems _Vol-1557_ was published under <A HREF="http://creativecommons.org/publicdomain/zero/1.0/">Creative Commons CC0</A>, do we still need to add the license information for it?

**Comment by S6savahd** [comment]
please elaborate what you mean: I still have what? the script? 

re. 1557: for all volumes with a specified license, we should have the right information, for the others without license we agreed to have no license. The point is all volumes should have a license.

**Comment by liyakun** [comment]
@S6savahd sorry, I mean the previous script to process the license information, but we can check during meeting. 

re. 1557: Okay.

**Comment by S6savahd** [comment]
https://creativecommons.org/publicdomain/zero/1.0/

here you can see what cc0 means: 
https://creativecommons.org/licenses/by/3.0/

**Comment by liyakun** [comment]
This issue is solved in the new dataset.
