### ISSUE TITLE
URLs not working

### ISSUE THREAD

**Issue by S6savahd** [ceurws/ToolsEswc#17]
some URLs with extra characters are not pointing to the right place, look at 
    ns2:hasSession in the vol-1

**Comment by S6savahd** [comment]
http://ceur-ws.org/Vol-1/#A.iD%C3%BCsterh%C3%B6ft a ns1:Person ;
    ns3:sameAs http://ceur-ws.org/persons/A.iD%C3%BCsterh%C3%B6ft ;
    ns1:made http://ceur-ws.org/Vol-1/#buchholz-et-al-long ;
    ns1:name "A. Düsterhöft" .

http://ceur-ws.org/Vol-1/#A.iSchaerf a ns1:Person ;
    ns3:sameAs http://ceur-ws.org/persons/A.iSchaerf ;
    ns1:made http://ceur-ws.org/Vol-1/#buchheit-et-al-long ;
    ns1:name "A. Schaerf" .

**Comment by liyakun** [comment]
this encoding issue is solved in the new dataset.
