### ISSUE TITLE
proceeding volume vs. events

### ISSUE THREAD

**Issue by S6savahd** [ceurws/ToolsEswc#2]
The URLs  for proceedings are mixed up with events.
For example, this ( http://ceur-ws.org/Vol-1/) is used for expressing the event as subject whereas it should be used for proceedings and instead a new URL should be created for event description as the subject e.g.,  http://ceur-ws.org/Vol-1/#event and not to have  http://ceur-ws.org/Vol-1/#proc.

**Comment by liyakun** [comment]
@S6savahd then this means we need to replace http://ceur-ws.org/Vol-1/#proc with http://ceur-ws.org/Vol-1/, and replace http://ceur-ws.org/Vol-1/ with http://ceur-ws.org/Vol-1/#event, right?

**Comment by S6savahd** [comment]
yes.

**Comment by liyakun** [comment]
done by post processing of the dataset, one example for Vol-1 is as follows

``` turtle
<http://ceur-ws.org/Vol-1/> a ns1:Proceedings;
    ns1:hasPart <http://ceur-ws.org/Vol-1/#beneventano-et-al-long>,
        <http://ceur-ws.org/Vol-1/#benn-long>,
        <http://ceur-ws.org/Vol-1/#bresciani-long>,
        <http://ceur-ws.org/Vol-1/#buchheit-et-al-long>,
        <http://ceur-ws.org/Vol-1/#buchholz-et-al-long>,
        <http://ceur-ws.org/Vol-1/#guetari-et-al-long>,
        <http://ceur-ws.org/Vol-1/#huber-long>,
        <http://ceur-ws.org/Vol-1/#hustadt-long>,
        <http://ceur-ws.org/Vol-1/#jeusfeld-long>,
        <http://ceur-ws.org/Vol-1/#krdb94-overview>,
        <http://ceur-ws.org/Vol-1/#lenzerini>,
        <http://ceur-ws.org/Vol-1/#norrie-et-al-long>,
        <http://ceur-ws.org/Vol-1/#schild-long>,
        <http://ceur-ws.org/Vol-1/#schmiedel-long>,
        <http://ceur-ws.org/Vol-1/#scholl>,
        <http://ceur-ws.org/Vol-1/#vossen-long> ;
    ns6:issued "1995-04-07T00:00:00+00:00"^^xsd:dateTime ;
    ns5:presentedAt <http://ceur-ws.org/Vol-1/#event> ;
    ns2:editor <http://ceur-ws.org/Vol-1/#FranziBaader>,
        <http://ceur-ws.org/Vol-1/#ManfrediA.iJeusfeld>,
        <http://ceur-ws.org/Vol-1/#MartiniBuchheit>,
        <http://ceur-ws.org/Vol-1/#WerneriNutt> .
```

**Comment by clange** [comment]
Thank you, looks great. Could you please provide a link to the code that performs the post-processing? I'd be interested to see it.

**Comment by liyakun** [comment]
Hi @clange , you can find it here [dataset/serializer.py](https://github.com/ceurws/ToolsEswc/blob/master/dataset/serializer.py).
