### ISSUE TITLE
mixing affiliation and name and missing the relation between them 

### ISSUE THREAD

**Issue by S6savahd** [ceurws/ToolsEswc#4]
e.g., http://ceur-ws.org/Vol-1155/

**Comment by liyakun** [comment]
Previously, the serialization result contians

``` rdf
<rdf:Description rdf:about="http://ceur-ws.org/Vol-1155/#AlexanderiGarc%C3%ADaiCastroFloridaiStateiUniversityUSA">
    <affiliation xmlns="http://swrc.ontoware.org/ontology/#"></affiliation>
    <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Person"/>
    <foaf:name>Alexander García CastroFlorida State UniversityUSA</foaf:name>
</rdf:Description>
```

This is caused by the original tool's method to recognize editor, it is now improved, and the result now is 

``` Turtle
<http://ceur-ws.org/Vol-1155/#AlexanderiGarc%C3%ADaiCastro> a foaf:Person ;
    ns5:place <http://dbpedia.org/resource/United_States> ;
    ns3:affiliation "Florida State University" ;
    foaf:name "Alexander García Castro" .
```

There are many cases the affiliation is using '(affiliation)' in the author of paper representation , now the result is changed as follows

> before: M. Rys (ETH Zürich), http://ceur-ws.org/Vol-2/#M.iRysi(ETHiZürich)
> 
> Now: M. Rys, http://ceur-ws.org/Vol-2/#M.iRysi

**Comment by S6savahd** [comment]
Great.
