### ISSUE TITLE
conferences should be represented as resources 

### ISSUE THREAD

**Issue by S6savahd** [ceurws/ToolsEswc#9]

**Comment by liyakun** [comment]
I did not remember clear about last discussion about this issue, maybe we did not saw it that moment. The conferences are already represented as resources, like

``` Turtle
<http://ceur-ws.org/Vol-1/#conf> a ns5:ConferenceEvent .
```

@S6savahd @clange is this the issue addressed? thanks.

**Comment by S6savahd** [comment]
let's keep the issue open until we check it again together or with Christoph, I also do not see a problem.

**Comment by S6savahd** [comment]
we can close this one also
